<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\PengajuanCuti;
use App\Models\Absensi;
use App\Models\Aset;
use App\Models\Pengumuman;
use Carbon\Carbon;
use Illuminate\Support\Facades\Log;

class RunDailyAutomation extends Command
{
    // Nama perintah yang akan dipanggil di terminal
    protected $signature = 'ldp:daily-automation';
    protected $description = 'Menjalankan tugas otomatis harian (Auto-Cuti & Peringatan Pajak Aset)';

    public function handle()
    {
        $hariIni = Carbon::today()->toDateString();

        // ==========================================
        // 1. AUTO-CUTI (Eksekusi Absensi Karyawan)
        // ==========================================
        $cutiBerjalan = PengajuanCuti::where('status_approval', 'Approved')
            ->whereDate('tanggal_mulai', '<=', $hariIni)
            ->whereDate('tanggal_selesai', '>=', $hariIni)
            ->get();

        $jumlahCuti = 0;
        foreach ($cutiBerjalan as $cuti) {
            // Cek agar tidak absen ganda di hari yang sama
            $sudahAbsen = Absensi::where('karyawan_id', $cuti->karyawan_id)
                ->whereDate('tanggal', $hariIni)
                ->exists();

            if (!$sudahAbsen) {
                Absensi::create([
                    'karyawan_id' => $cuti->karyawan_id,
                    'tanggal' => $hariIni,
                    'status' => 'Cuti',
                    'catatan' => 'Auto-generated by System: ' . $cuti->jenis_cuti,
                ]);
                $jumlahCuti++;
            }
        }

        // ==========================================
        // 2. PERINGATAN PAJAK ASET (H-30)
        // ==========================================
        $hMin30 = Carbon::today()->addDays(30)->toDateString();
        $asetExpired = Aset::whereDate('tgl_expired_pajak', $hMin30)->get();

        $jumlahAset = 0;
        foreach ($asetExpired as $aset) {
            Pengumuman::create([
                'judul' => '🚨 PERINGATAN PAJAK ASET: ' . $aset->kode_aset,
                'konten' => "Pajak/Lisensi untuk aset **{$aset->nama_aset}** ({$aset->kode_aset}) akan habis tempo pada **{$aset->tgl_expired_pajak}**. Mohon tim GA/Admin segera melakukan perpanjangan.",
                'pembuat_id' => 1, // Dibuat otomatis atas nama Super Admin (ID 1)
                'target_audiens' => 'Global', 
                'tgl_mulai' => $hariIni,
                'tgl_selesai' => $hMin30,
                'tipe_banner' => 'Penting',
                'is_aktif' => true,
            ]);
            $jumlahAset++;
        }

        // Catat hasil kerja robot di terminal dan log sistem
        $pesan = "Daily Automation Selesai: {$jumlahCuti} Cuti dieksekusi, {$jumlahAset} Peringatan Aset dibuat.";
        $this->info($pesan);
        Log::info($pesan);
    }
}